package org.example.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Booking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String email;
    private String mobile;
    private LocalDateTime timestamp;

    @ManyToMany
    @JoinTable(
            name = "booking_seats",
            joinColumns = @JoinColumn(name = "booking_id"),
            inverseJoinColumns = @JoinColumn(name = "seat_id")
    )
    private List<Seat> seats;

    // ✅ --- THIS IS THE FIX --- ✅
    // Add this custom helper method. It is NOT generated by Lombok.
    // It takes the list of Seat objects and transforms it into a list of seat number strings.
    public List<String> getSeatNumbers() {
        if (seats == null) {
            return new ArrayList<>();
        }
        return seats.stream()
                .map(Seat::getSeatNumber)
                .collect(Collectors.toList());
    }
}

